name: read secret
on:
  workflow_run:
    workflows:
      - on_pr
    types:
      - requested # I recommend this because sometimes issues can arise with external submissions requiring permission to run the bot, but with this the workflow_run will be triggered regardless

jobs:
  desired-action:
    runs-on: ubuntu-latest
    name: Desired Action
    permissions:
      id-token: write
      contents: read
    steps:
#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
#          aws-region: eu-west-1
#      - name: Run AWS Pipeline
#        uses: openhwgroup/aws-codebuild-run-build@master
#        with:
#          project-name: dummy
#          hide-log: true
#
      - name: access secret
        env: 
          SECRET: ${{ secrets.MY_SECRET }}
          ID: ${{github.event.workflow_run.id}}
          NAME_BASE: ${{ github.event.pull_request.base.repo.full_name }}
          NAME_HEAD: ${{ github.event.pull_request.head.repo.full_name }}
          NAME_REPO: ${{ github.repository }}
        shell: bash
        run: echo "$SECRET"; echo "$ID"; echo "$NAME_BASE";  echo "$NAME_HEAD";  echo "$NAME_REPO"
#        uses: <your-action>
#        id: desired-action
#        with:
#          GITHUB-TOKEN: ${{ secrets.TOKEN }}
#          WORKFLOW-ID: ${{github.event.workflow_run.id}}

