name: aws
on:
  push:
    branches:
      - 'dev'

jobs:
  run_tests:
    if: ${{ github.actor == 'ekatre' }}
    runs-on: ubuntu-latest
    name: run tests
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Run AWS Pipeline
        run: exit 0
