name: automerge

on:
  workflow_run:
    workflows: [aws]
    types:
      - completed

jobs:
  create_pr:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/create-pull-request@v4
        with: 
          commit-message: automerge to master
          title: Automerge to master
          body: auromerge to master
          branch: dev
          base: main          
