name: automerge

on:
  workflow_run:
    workflows: [aws]
    types:
      - completed

jobs:
  merge_to_master:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: peter-evans/create-pull-request@v4
        with: 
          commit-message: automerge to master
          title: Automerge to master
          body: auromerge to master
          branch: master
          base: dev        
