name: merge_to_dev
on: 
  pull_request_review:
    types: [submitted]
jobs:
  check_target:
    if: ${{ github.event.review.state == 'approved' }}
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.event.pull_request.base.ref == 'dev' }}
        run: exit 0
      - if: ${{ github.event.pull_request.base.ref != 'dev' }}
        run: exit 1
